version: 7.0.{build}

branches:
  only:
    - master

image: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

before_build:
  - nuget restore
  
build:
  project: Migrator.sln

test: off

artifacts:
  - path: '**\DotNetProjects.Migrator*.*nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: KC79cwbPGXPstkkHjylej8XZl/4CKdENSy/SF0wnkuU6CV6fVkK2ivDm1WzrIgo7
  artifact: /.*DotNetProjects\.Migrator.*nupkg/
  
  
  
